### ISSUE TITLE
problem po aktualizacji 

### ISSUE THREAD

**Issue by Mati16** [nightscout/nightscout.github.io#102]
Witam mam problem z połączeniem się z nightscout po aktualizacji. po przeprowadzonej aktualizacji w portalu heroku- zgodnie z instrukcja która była umieszczona na stronie http://nightscout.pl/. wyskakuje mi informacja 
![IMG_0158](https://user-images.githubusercontent.com/70483295/104225701-077d5e80-5447-11eb-929e-1e8a9ba0d84a.JPG)

**Comment by psonnera** [comment]
https://nightscout.github.io/troubleshoot/connection_string/#mongodb_uri-missing

**Comment by psonnera** [comment]
I see your site it up. Closing the problem. Dołącz do grupy https://www.facebook.com/groups/cgminthecloud, aby uzyskać pomoc.
