### ISSUE TITLE
UpdateView1.png ... UpdateView5.png are missing for https://nightscout.github.io/pages/update-fork/

### ISSUE THREAD

**Issue by PmE8HW0KRfqa** [nightscout/nightscout.github.io#106]

**Comment by PmE8HW0KRfqa** [comment]
See my re-open comment below.

**Comment by PmE8HW0KRfqa** [comment]
UpdateView1.png ... UpdateView5.png are missing for https://nightscout.github.io/pages/update-fork/

**Comment by psonnera** [comment]
Wow thanks, just restored the files. Sorry about it. They're belonging to an http page not included in MKDocs.

**Comment by psonnera** [comment]
Fixed and merged. Thanks again.

**Comment by PmE8HW0KRfqa** [comment]
> Fixed and merged. Thanks again.

No, thank you!
