### ISSUE TITLE
ce16006_f.gif file missing on https://nightscout.github.io/pages/update-fork/

### ISSUE THREAD

**Issue by PmE8HW0KRfqa** [nightscout/nightscout.github.io#107]
When I run this [page](https://nightscout.github.io/pages/update-fork/) against a github username that is already up to date, there's a broken image link:

`<img src="http://opensourcebridge.org/wp-content/uploads/2009/04/ce16006_f.gif">`

**Comment by psonnera** [comment]
Yes, you're right, I saw that yesterday. Pending fix.

**Comment by psonnera** [comment]
@sulkaharo do you remember what was displayed?

**Comment by sulkaharo** [comment]
I have no idea. Big green checkmark?

**Comment by sulkaharo** [comment]
<img width="485" alt="Screenshot 2021-02-11 at 22 36 17" src="https://user-images.githubusercontent.com/1001330/107695663-95a06b00-6cb9-11eb-9e44-43060c54d3c2.png">

**Comment by sulkaharo** [comment]
![image](https://user-images.githubusercontent.com/1001330/107695820-c8e2fa00-6cb9-11eb-939a-0ca591e12100.gif)

**Comment by sulkaharo** [comment]
(The star is the one that was shown earlier. Not sure if it makes sense.)

**Comment by psonnera** [comment]
Restored
