### ISSUE TITLE
abertura de conta nightscout

### ISSUE THREAD

**Issue by julianomuller** [nightscout/nightscout.github.io#109]
Aparece pra mim..... nighstcout esta tendo problemas..
erros ocorridos durante a inicializacao.
nao e possivel conectar o mongo:
mongodb_url parece invalido: url não tem nome de host, nome de domínio e tld.

por favor, como resolver isso. obrigado.

**Comment by psonnera** [comment]
Look here https://nightscout.github.io/troubleshoot/connection_string/ and join us for help in https://www.facebook.com/groups/cgminthecloud/
