### ISSUE TITLE
Remote notifications/ Pushover page

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#119]
https://nightscout.github.io/nightscout/pushover/

Hi @psonnera , this page came up in a different discussion about Loopdocs (https://github.com/LoopKit/loopdocs/issues/245). Is this a part of the current NS documentation? I could not find it through the menus, just by searching. There are lots of broken image links here!

**Comment by psonnera** [comment]
You're definitely right. It was from the original Loop docs and is not linked anymore. Will fix it ASAP.

**Comment by psonnera** [comment]
Restored images https://github.com/nightscout/nightscout.github.io/commit/97a12347d6d66964eb8a57ccc99b2396f54e2659 now just need to find where to fit this page in the menu.

**Comment by marionbarker** [comment]
Please note that the instructions for obtaining API Secret hash on the IFTTT page are incorrect.

And please see https://github.com/LoopKit/loopdocs/issues/245

A number of pages from LoopDocs / Nightscout section are being modified to refer to the NS docs (leaving the pages for now but with content removed in favor of links to your docs.)
