### ISSUE TITLE
Site navigation

### ISSUE THREAD

**Issue by marionbarker** [nightscout/nightscout.github.io#120]
The same page security.md is  found under the Configure Menu and under the Use Menu. This causes a problem when using Next (or the n key) and Previous (or the p key).

Using Next and Previous with this arrangement of mkdocs.yml means you skip items below security in the Configure menu when going forward (Next) and get in an infinite loop as soon as you get to the security page under Use menu when going backwards (Previous).

**Comment by psonnera** [comment]
https://github.com/nightscout/nightscout.github.io/commit/72c503cc646d186b54afe26f86c07361c390ea31
