### ISSUE TITLE
Instructions update

### ISSUE THREAD

**Issue by Onsekone** [nightscout/nightscout.github.io#122]
Are there up to date instructions for setting up Nightscout page? The view and functions in Mongodp has changed quite a bit since linked instructions were made. Thanks.

https://nightscout.github.io/update/redeploy/#step-1-cleanup-github

[Instructions.pdf](https://github.com/nightscout/nightscout.github.io/files/7147384/Instructions.pdf)

**Comment by psonnera** [comment]
The sequence should still be valid. I agree many sites changed graphics.
This issue is real and will be taken care of. Need time. Thanks!

**Comment by Onsekone** [comment]
Thanks. I'm kind of stuck here because function on "connect" button has been changed.
