### ISSUE TITLE
Release 14.2.3 broke remote overrides

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#128]
Release 14.2.3 broke remote overrides for iOS Loop.

Someone elses screenshot below. I got similar results, but forgot to screenshot before rolling back to my previous deploy. 

In my case, dev as of very recently was working.

![Screenshot_20211025-011053_Facebook](https://user-images.githubusercontent.com/63544115/138616698-8cc754dc-094f-4b71-b416-30032b35b9e0.jpg)

**Comment by bjornoleh** [comment]
@sulkaharo 
@bewest

**Comment by bjornoleh** [comment]
Sorry, this Issure was created in the wrong repository, should have been in nightscout/cgm-remote-monitor.

Closing this issue, and someone else just made a new issue report in the correct repo:
https://github.com/nightscout/cgm-remote-monitor/issues/7141

**Comment by bewest** [comment]
Thanks for the feedback, @bjornoleh.  We've prepared a new set of patches in the dev branch.  Would you be able to check if the dev branch restores the function you expect with Loop?
https://github.com/nightscout/cgm-remote-monitor/pull/7144
https://github.com/nightscout/cgm-remote-monitor/pull/7139

**Comment by bjornoleh** [comment]
> Thanks for the feedback, @bjornoleh. We've prepared a new set of patches in the dev branch. Would you be able to check if the dev branch restores the function you expect with Loop? [nightscout/cgm-remote-monitor#7144](https://github.com/nightscout/cgm-remote-monitor/pull/7144) [nightscout/cgm-remote-monitor#7139](https://github.com/nightscout/cgm-remote-monitor/pull/7139)

Thanks @bewest, I just deployed dev, and it is indeed working as expected regarding remote overrides in iOS Loop.
