### ISSUE TITLE
Docs Site Installation Instructions Omits bridge in recommended ENABLE variable

### ISSUE THREAD

**Issue by jmb496** [nightscout/nightscout.github.io#129]
Not sure if this is the right place for this, but the installation instructions on the docs site is missing "bridge" in step 4k when setting up the ENABLE variable.  Seemed to prevent me from getting DEXCOM share data until I went through the troubleshooting page and identified it as missing.

**Comment by psonnera** [comment]
Thank you for this, will be corrected next release.

**Comment by psonnera** [comment]
Fixed in https://github.com/nightscout/nightscout.github.io/commit/8b03ba67edce9315a947e43a64adcdbe4da26253
