### ISSUE TITLE
Troubleshooting DST and time zone related issues

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#131]
Hi, there is already a mention of at least one symptom of not having time zone set in NS:

http://nightscout.github.io/troubleshoot/troublehoot/#basal-is-shifted-in-time

There is also another one that could have been mentioned. I have seen this before, and it re-emerged now after the end of DST. 

In my case (with iOS Loop data) the Day to day report did not display basal or IOB/COB from the time before end of DST:

![image](https://user-images.githubusercontent.com/63544115/140316773-cdadb58b-4075-413a-b719-39c17166a09c.png)

Setting the time zone in Profile editor brought the data back.

**Comment by psonnera** [comment]
https://github.com/nightscout/nightscout.github.io/commit/086b41b00b2577d7431254a69e01ff9b79f97b35
