### ISSUE TITLE
Material Theme for MkDocs for better search features

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#132]
FYI: Loopdocs very recently switched to the Material Theme for MkDocs after this discussion: https://github.com/LoopKit/loopdocs/issues/284

"Material" theme replaced "Flatly" theme. The new theme is still supported, unlike Flatly. One significant difference is that the search feature is greatly improved.

**Comment by psonnera** [comment]
I will make some tests to see how the result looks like. One feature I would like is a 2 level menu to declutter vendors. I will submit the resulting preview to @bewest and @sulkaharo once done.

**Comment by psonnera** [comment]
Preview is available at https://psonnera.github.io/nightscout.github.io/ (some glitches to be fixed like the icon) and I chose a black theme matching the logo. @bewest @sulkaharo your approval required to change to this theme.
