### ISSUE TITLE
Documentation on Smartwatches running Wear OS 3.x

### ISSUE THREAD

**Issue by pieter-de-ceuninck** [nightscout/nightscout.github.io#138]
Hi all,
does anyone have experience with getting nightscout data as a watchface for the Samsung Galaxy Watch 4, that runs on Wear OS 3? I have looked in many places, but all watchfaces i found, stop at Wear OS 2. That is also where the nightscout documentation stops :-) 
thx,
Pieter

**Comment by psonnera** [comment]
Same strategy than Wear 2: use Wear installer.

**Comment by psonnera** [comment]
https://xdrip.readthedocs.io/en/latest/smartwatch/wearinstall/
