### ISSUE TITLE
Mute alarms via API call

### ISSUE THREAD

**Issue by afly007** [nightscout/nightscout.github.io#139]
I'm new to Nightscout since we have a new T1D diagnosis in the family in the last 3 months.

I have a number of Fire Tablets, one on each floor, around the house so we can keep an eye on values throughout the day.

When we get a low alert we have to go around to each tablet and Silence the alert manually.

Is there a way to manually silence the alert via an API call?  It'd be perfect to call via Home Assistant, especially when working from home and with everyone back to school.

**Comment by psonnera** [comment]
Might be a good question in Discord https://discord.gg/rTKhrqz
