### ISSUE TITLE
if you weren't aware vpn kills nightscout

### ISSUE THREAD

**Issue by AMXeno** [nightscout/nightscout.github.io#141]
you have to resync and re pair your cgm if you use a vpn iOS

**Comment by bryanw20** [comment]
IDK if it helps; I'm using surfshark on my android, xdrip, dexcom & heroku(?) upload & seems to be working fine

**Comment by AMXeno** [comment]
Sorry for lack of clarification, Norton secure vpn causes it to say APS offline. After turning it off or reloading the page a few times it usually resolves, otherwise I have to re sync it. Using a different app like nightscout X or nightguard seems to resolve this completely

**Comment by psonnera** [comment]
@AMXeno does this issue require documentation modification somewhere?
