### ISSUE TITLE
Nightscout interaction with other apps

### ISSUE THREAD

**Issue by bryanw20** [nightscout/nightscout.github.io#142]
Hi, IDK where to post/ask; looking to see if there's a list; (similar to the watches list), if not how/where to create a list of apps/sites that interact with NS; like xdrip uploads, & diabetes:m syncs data; what else is out there?
like how Fitbit interacts with dozens of apps.

I tried the FB in the cloud & xdrip groups, and the discord chat room.

admin/dev feel free to close this message asap; just looking for more interaction

**Comment by psonnera** [comment]
Feel free to let me know what needs to be added [here ](https://nightscout.github.io/uploader/setup/) and [here ](https://nightscout.github.io/nightscout/downloaders/) or [here](https://nightscout.github.io/nightscout/wearable/)
