### ISSUE TITLE
Date issue in reporting

### ISSUE THREAD

**Issue by HansBrasT1** [nightscout/nightscout.github.io#144]
Hello,  have the following issue in the reporting tool of Nightscout:
I select "Today"and the Percentile Chart and I get the chart with values of yesterday. And when I select the date of tomorrow and the percentile chart I get the chart with values of today.

![Nightscout values today](https://user-images.githubusercontent.com/55949580/166904428-95f604da-90b5-43d8-98f2-117817c6a26a.png)

![Nightscout values yesterday](https://user-images.githubusercontent.com/55949580/166904446-563faf08-f35e-465d-8a3b-c1bae2797a0d.png)

What can be the cause of this issue?
Thank you in advance,
Hans

**Comment by psonnera** [comment]
Did you eventually get it fixed? If yes, please share.
