### ISSUE TITLE
Dead link (404) in Maker instructions 

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#145]
http://nightscout.github.io/nightscout/setup_variables/#ifttt-maker

Dead link here:

see the [full list of events](https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/plugins/maker-setup.md#events)

This is probably the correct link (?):

https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/maker-setup.md#events

**Comment by psonnera** [comment]
Thank you!
