### ISSUE TITLE
master/dev versions don't work with AndroidAPS (at least on my end)

### ISSUE THREAD

**Issue by moralvoltage** [nightscout/nightscout.github.io#146]
The Heroku  app crashes whenever NS is enabled on AndroidAPS.

I got it running using the 0.11 release. It'd be nice to have that written somewhere in the [tutorial](https://nightscout.github.io/nightscout/new_user/) since, I suppose, many people following it don't know much about git (and SPECIALLY since one of the screenshots shows the selected branch as `master`)
![image](https://user-images.githubusercontent.com/109753440/180325671-4b2f19c4-e946-43ca-96a0-a6b2461bf9b0.png)

**Comment by psonnera** [comment]
I believe this is being worked on https://github.com/nightscout/cgm-remote-monitor/commit/46250506651ea85b92e8bbf3b2ed93fdb9b7404b and should be fixed with AAPS 3.1
