### ISSUE TITLE
auto build/publish workflow

### ISSUE THREAD

**Issue by bewest** [nightscout/nightscout.github.io#151]
Is the gh-pages branch supposed to build and publish itself automatically or is there a way to manually kick off the workflow?  There's been some nice edits over the last few days that I'm eager to have published.  I can have a look at helping with the automated flow if needed, assuming the idea is to have the main `source` branch automatically published.

**Comment by psonnera** [comment]
I tried to implement this https://github.com/nightscout/nightscout.github.io/pull/125in the past but it resulted in some pages having text corruption so I preferred to remove it and gh-deploy manually. We can think about restoring it in the future after someone takes the time to test it. I am reluctant to have this implemented unless more people are collaborating to the actual contents of the documentation and not only general guidelines and philosophical changes. Few people understand that documenting step by step is taking hours and hours.

**Comment by marionbarker** [comment]
If you read the publish file it’s still configured to publish manually. Someone with privileges can kick it off. 

https://github.com/nightscout/nightscout.github.io/blob/source/.github/workflows/publish.yml

If you look at LoopDocs version, you’ll see it’s set up to be automatic. 

- M

On Sep 1, 2022, at 4:39 PM, Ben West ***@***.***> wrote:

﻿
Is the gh-pages branch supposed to build and publish itself automatically or is there a way to manually kick off the workflow? There's been some nice edits over the last few days that I'm eager to have published. I can have a look at helping with the automated flow if needed, assuming the idea is to have the main source branch automatically published.
