### ISSUE TITLE
Document Railway deployment

### ISSUE THREAD

**Issue by psonnera** [nightscout/nightscout.github.io#152]
Moving https://github.com/nightscout/cgm-remote-monitor/pull/7319#pullrequestreview-1092775832 to the right repo

**Comment by psonnera** [comment]
A draft is present in https://github.com/nightscout/nightscout.github.io/blob/source/docs/vendors/railway.app/new_user.md with related screenshots in img. Feel free to edit the .md. Provided instructions do not work as the script doesn't deploy.
@sbmsr

**Comment by asonnera** [comment]
@sbmsr removing the credit card section, if you follow [Step 2](https://nightscout.github.io/vendors/railway.app/new_user/#step-2-create-a-railway-account) to create the account you already have 500 hours. Also, lettering substeps has been requested by @TerrysNightscout.

**Comment by psonnera** [comment]
@bewest ideally a button should be present on https://github.com/nightscout/cgm-remote-monitor#readme to deploy in Railway as templates are really nice and simple to create. Now the issue I have is that Railways templates are privately hosted and can't be viewed except by their owner. This means we need a trusted Railway user, who will guarantee the template presence for a long time, or to get it published by Railway. https://github.com/railwayapp/templates#submitting-a-template
