### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by psonnera** [nightscout/nightscout.github.io#154]
@bewest there is a lot of probably useless material in this repo that would deserve cleanup. For example the https://github.com/nightscout/nightscout.github.io/tree/source/src folder might benefit someone knowledgeable removing unnecessary contents.
Also https://github.com/nightscout/nightscout.github.io/tree/source/docs/vendor is that necessary?

**Comment by bewest** [comment]
The `src` folder was used with docpad, if I recall correctly.  I believe `vendor` assets may be needed for the pages present on the site but not built by mkdocs.  These include the autoconfigure page and the update-fork page.  I still refer people to these pages.  It's probably safe to remove `src`.  Maybe move both of them to `.vendor` and `.src` for awhile, and see how things go?

**Comment by psonnera** [comment]
OK, I know vendor will hit cgm-remote-monitor links (better not touch it) so first shot is env to .env
Funny stuff in there https://github.com/nightscout/nightscout.github.io/blob/57c810ca6b4a352611fc6e28e2ff1a5a802d9ac3/src/documents/index.html.jade#L25
