### ISSUE TITLE
QNAP NAS deployment

### ISSUE THREAD

**Issue by psonnera** [nightscout/nightscout.github.io#163]
All input welcome.

**Comment by robertrub** [comment]
Please look in the shared doc below. 

https://docs.google.com/document/d/1zpF6Y3kPQqc9KOsClIQt686HDLhGfFxwz4vGfq8E254/edit?usp=sharing

This has NOT been tested thoroughly (it is working great on my QNAP NAS). Please write your comments to the step  y step in this issue.

**Comment by psonnera** [comment]
Thanks!

How to install NightScout and MongoDB on a personal QNAP NAS

This method has not been tested widely. Please leave a message on Discord if this how to needs modifications

In the QNAP NAS, install Container Station.

On your computer create a text file containing the below text, adapted to your usage (secret api, name, variable settings etc).

version: '3.9'

services:
  mongo:
    container_name: nightscout-mongodb
    image: mongo:4.4
    restart: 'unless-stopped'
    volumes:
      - /share/CACHEDEV1_DATA/Container/MongoDB/nightscout-mongodb:/data/db:cached
  nightscout:
    image: nightscout/cgm-remote-monitor:14.2.6
    container_name: nightscout
    restart: 'unless-stopped'
    depends_on:
      - mongo
    ports:
      - '1337:1337'
    environment:
      ### Variables for the container
      NODE_ENV: production
      TZ: Etc/UTC
      INSECURE_USE_HTTP: 'true'

      ### Required variables
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout
      API_SECRET: ENTER YOUR SECRET API HERE

      ### Features
      ENABLE: careportal boluscalc food bwp basal rawbg iob cob sage cage iage pushover bgi pump openaps ar2
      DEVICESTATUS_ADVANCED: true
      SHOW_FORECAST: openaps
      PUMP_FIELDS: reservoir battery clock

      # AUTH_DEFAULT_ROLES (readable) - possible values readable, denied, or any valid role name.
      AUTH_DEFAULT_ROLES: denied

      # For all other settings, please refer to the Environment section of the README
      # https://github.com/nightscout/cgm-remote-monitor#environment
      DISPLAY_UNITS: mg/dl
      TIME_FORMAT: 24
      CAGE_WARN: 70
      CAGE_URGENT: 80
      IAGE_WARN: 70
      IAGE_URGENT: 80
      SAGE_WARN: 234
      SAGE_URGENT: 240
      CUSTOM_TITLE: ENTER YOUR NS WEB PAGE TITLE HERE
      THEME: colors
      SHOW_FORECAST: 'false'
      ALARM_TIMEAGO_WARN: 'off'
      ALARM_TIMEAGO_URGENT: 'off'
      ALARM_HIGH: 'off'
      ALARM_LOW: 'off'
      ALARM_URGENT_HIGH: 'off'
      ALARM_URGENT_LOW: 'off'


Open Container Station and click on Create then + Create application button. 

Give an app name (just use letters and don’t use space to be safe), delete the text in the box and paste the text above adapted to your needs. Click on Validate and once it is validated, click create. 

This will create your app with 2 containers (NS and Mongo). It will work correctly but you will not be able to change the yaml data you have entered to change variables, to update NS etc. We’ll “cheat” in order to have access to the yaml.

Stop your app. Once it has stopped, start the Create an app process above a second time with another app name. You’ll get an error, don’t worry. Once you have the error, delete the FIRST app you have created. This will leave you with the second app and a yaml that you can now modify using the square with a pen icon. Open the yaml with that icon, validate and then hit create. This time, it will create the app without an error and with access to the yaml ;)  

The data of your database will be in the NAS drive (DataVolume1), \Container\MongoDB\nightscout-mongodb\

If you use in your navigator YOUR_NAS_IP:1337 you should see the NS page (it will ask you to fill a profile)


Now that you have a working NS and MongoDB, you need to create the access.I

In Control Panel, open LAN then click on Reverse proxy. Add a new rule. Source will be HTTP (do not use HTTPS), use an unused port (we’ll use 4443 for this exemple). For the Destination, use WebSocket and port 1337. A request arriving to the NAS 4443 port will be directed to Docker 1337 (thus to NS). 

If you use in your navigator YOUR_NAS_IP:4443 you should see the NS page. For the moment, all is in HTTP only.

Next step is to open your NS to the internet so that xDrip+ or AAPS can access it. On your router, create a new rule “external 4443 (can be another port) to internal 4443 (or another port you defined in the Reverse proxy), TCP protocol” 

If all is working as it should, then https://your_nas_name.myqnapcloud.com:4443/ should bring you to the NS page. You need to have activated MyQNAPCloud service in the NAS of course.

Next step will be to import your actual MongoDB (on Atlas) to your Mongo DB on your NAS… 

Pause the uploads to NS in xDrip+ and/or AAPS

In the Container station, next to your app name, on the left of the 3 cubes, click on the arrow in order to open and see the two containers of the app.

On the nightscout-mongodb line, click on the >_ icon to enter terminal commands and enter the command below (after having added tout MongoDB URI). Leave the quotes as they are.

mongodump --uri="YOUR MONGO URI HERE/temp"

Wait as it takes some time to import all your data from your mongoDB on Atlas to your NAS. Once it has finished importing (no action for 30+ sec), close the window.

Click again on the same >_ icon and enter the command line below.

mongorestore --drop -v --db nightscout dump/temp

Wait again, it will take a longer time to import all the data into your own MongoDB and create the indexes. Once it stops (no action for over 30 sec), you can close the window.

In xDrip+ and/or AAPS, enter https://your_nas_name.myqnapcloud.com:4443/ (in xDrip+ add /api/v1/ at the end of the line) and unpause the NS uploads. It should upload normally to the NS on your NAS. You can also check on your NS page that you wan see the records of the past weeks.
