### ISSUE TITLE
Add Dev build info for Azure migration

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/nightscout.github.io#165]
I think the information for dev build can be also added on this page https://nightscout.github.io/vendors/azure/migrate/ on step J)

Stable
`nightscout/cgm-remote-monitor:latest`

Dev Build
`nightscout/cgm-remote-monitor:latest_dev`

**Comment by psonnera** [comment]
Yes, there is still so much work to do.
I don't like the idea to adding dev at this point but know I need to add dev in other vendors platforms instructions.

**Comment by psonnera** [comment]
Implementing changes in https://nightscout.github.io/update/dev_branch/ for Railway I believe you're right as Azure (Docker) doesn't use GitHub, so yes. Let me fix that now.

**Comment by parapenT1sta** [comment]
I am using Dev version and I got the tag from here:
https://hub.docker.com/r/nightscout/cgm-remote-monitor/tags

**Comment by psonnera** [comment]
Yes I know
