### ISSUE TITLE
[Improvement] Add Weight and Blood Pressure events

### ISSUE THREAD

**Issue by idalioreis** [nightscout/nightscout.github.io#172]
Hi
I think it would be important to condense all the information in just one place that is usually needed in a doctor's appointment. In diabetes, weight and blood pressure are important data to record for monitoring possible diseases.
These fields could be added to events.

Thanks

**Comment by psonnera** [comment]
This is only the documentation repository. Try a feature request https://github.com/nightscout/cgm-remote-monitor/issues/new/choose
