### ISSUE TITLE
alarm trigger crossing threshold vs going in 1 direction

### ISSUE THREAD

**Issue by djhurlburt** [nightscout/nightscout.github.io#176]
I hope this is the right forum to post this question (before raising it as an issue): I did post this question on the Facebook site (CGM in the Cloud) but no response. I have nightscout running on Google Cloud server and figured out how to get IFTTT to trigger stuff through my Alexa device. What I'm finding though is that (a) it is using 'predicted' BG to send a maker trigger, despite having "ALARM_TYPE" set to "simple"; and (b) it seems a "maker" trigger is sent regardless of whether the data is going up or down across a threshold. In other words, when she goes below "BG_TARGET_BOTTOM" the maker trigger is sent, but then if she treats and goes above "BG_TARGET_BOTTOM", another trigger is sent. I only care if she is going below the "BG_TARGET_BOTTOM", but not sure if there is a setting that will enable only going below the value to send a maker trigger?

**Comment by psonnera** [comment]
Sorry I completely missed this one, you might want to ask in Discord if you haven't found a solution by now. https://discord.gg/zg7CvCQ
