### ISSUE TITLE
QNAP NAS deployment 32bit

### ISSUE THREAD

**Issue by suzaku0k** [nightscout/nightscout.github.io#178]
Please look in the shared doc below. 

https://docs.google.com/document/d/1zpF6Y3kPQqc9KOsClIQt686HDLhGfFxwz4vGfq8E254/edit?usp=sharing

This has NOT been tested thoroughly (it is working great on my QNAP NAS). Please write your comments to the step  y step in this issue.

_Originally posted by @robertrub in https://github.com/nightscout/nightscout.github.io/issues/163#issuecomment-1296150254_
            
any chance of getting it done with ts 231p (32bit) model? I'm getting whats below when following your guide
Background task error for application_custom nightscout1: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by robertrub** [comment]
The requested image's platform is based on Intel 64 bits CPU.
So you'd need to find a docker image that was build for a 32 bits CPU. 
Don't know where that is though.
