### ISSUE TITLE
potentially misconfigured settings for mongo db on docker compose

### ISSUE THREAD

**Issue by rdpeake** [nightscout/nightscout.github.io#179]
Hello,

I set up a digital ocean instance of nightscout using the docker version. i followed the instructions and used the https://github.com/nightscout/nightscout.github.io/blob/source/docs/nightscout/docker-compose.yml version mentioned in the documents.

However this has since been flagged by the security system of digital ocean as having a potentially exposed mongo db instance. i followed their instructions and it doesn't appear that i can access it externally, but the fact that the system host was able to detect this has me caution that there may actually be something i have missed with my install.

is there a change i should be making here?

**Comment by psonnera** [comment]
Yes, I'm working on it. Comment out the ports (all lines)
ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
      - "28017:28017"

**Comment by psonnera** [comment]
Commented out https://github.com/nightscout/nightscout.github.io/commit/df41727d9ba45f2cff7d2577e62363d4d45cdb6a
