### ISSUE TITLE
OBSCURED and OBSCURE_DEVICE_PROVENANCE variables 

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#181]
I believe the OBSCURED and OBSCURE_DEVICE_PROVENANCE variables have been included in NS master for a while now, although the docs indthey are still in dev. 

And the explanation is not all that self explanatory either, perhaps @bewest could expand on this ever so slightly?

I also can’t find any mention of the variables in the NS repository readme:
https://github.com/nightscout/cgm-remote-monitor/tree/master#environment

“The variables below belong to dev branch until further notice.

OBSCURED (bridge) - Obscure data source when using bridge uploader.
OBSCURE_DEVICE_PROVENANCE (dexcom-dont-own-my-body-data) - Self explanatory.”

Docs:
https://nightscout.github.io/nightscout/setup_variables/?h=obscure#bridge-share2nightscout-bridge

14.2.6 Release notes:
https://github.com/nightscout/cgm-remote-monitor/releases/tag/14.2.6

**Comment by psonnera** [comment]
Good catch. Thanks.
