### ISSUE TITLE
update stack for heroku app

### ISSUE THREAD

**Issue by steficonev** [nightscout/nightscout.github.io#184]
https://nightscout.github.io/en/latest/update/upd_stack.html

is not working! I need this info so much:( pls

**Comment by psonnera** [comment]
I have some problems with the links yes https://nightscout.github.io/update/upd_stack.html but where did you find that link?

**Comment by steficonev** [comment]
In the American group in Facebook CGM in the cloud. I really need this
instruction:(

**Comment by psonnera** [comment]
@steficonev try the link I copied above

**Comment by steficonev** [comment]
The link is working now:) I am going to try it! Thank you!

**Comment by psonnera** [comment]
Fixed documentation broken links using dirhtml build instead of html
