### ISSUE TITLE
Request update in /source/docs/vendors/heroku/migrate.md - the railway section should note that it is no longer free

### ISSUE THREAD

**Issue by SethDG** [nightscout/nightscout.github.io#191]
The page here /vendors/railway/new_user/ does a good job describing the situation for railway.  But it's confusing if users look at /source/docs/vendors/heroku/migrate.md .  That page has conflicting information because it still describes railway as free

**Comment by psonnera** [comment]
Thanks for bringing this to my attention. Wording fixed https://github.com/nightscout/nightscout.github.io/commit/08dadf561dda498a7ad763c23b11355267cc577c
