### ISSUE TITLE
Add Caddy as remote proxy in Docker method

### ISSUE THREAD

**Issue by psonnera** [nightscout/nightscout.github.io#193]
https://github.com/Alderskog/nightscout-in-OCN thanks @Alderskog

**Comment by psonnera** [comment]
https://github.com/nightscout/nightscout.github.io/commit/d2ab0773a3a04cce3cb621cc8c6fb1cf12060384

**Comment by logangreenwood** [comment]
Brenda On Jul 10, 2023, at 1:08 AM, Patrick Sonnerat ***@***.***> wrote:﻿
https://github.com/Alderskog/nightscout-in-OCN thanks @Alderskog

**Comment by logangreenwood** [comment]
What’s wrong with my site?Brenda On Jul 10, 2023, at 1:08 AM, Patrick Sonnerat ***@***.***> wrote:﻿
https://github.com/Alderskog/nightscout-in-OCN thanks @Alderskog

**Comment by psonnera** [comment]
@logangreenwood are you using Caddy with Docker?

**Comment by logangreenwood** [comment]
I’m not sure what that means, I’m sorry. I use this to be able to see my sons blood sugar level. Brenda On Jan 18, 2024, at 12:27 AM, Patrick Sonnerat ***@***.***> wrote:﻿
@logangreenwood are you using Caddy with Docker?

**Comment by psonnera** [comment]
@logangreenwood where do you host your Nightscout? The final part of the URL you use to open your site, like heroku.com/railway.app/???

**Comment by logangreenwood** [comment]
Heroku But it’s working now, thank you for trying to help. I’m lost with this sort of stuff. I don’t see how i even got the site up to begin with. Brenda On Jan 18, 2024, at 1:54 PM, Patrick Sonnerat ***@***.***> wrote:﻿
@logangreenwood where do you host your Nightscout? The final part of the URL you use to open your site, like heroku.com/railway.app/???
