### ISSUE TITLE
Nightscout APN issue in Northflank build

### ISSUE THREAD

**Issue by GraysonHunterNZ** [nightscout/nightscout.github.io#194]
I am having an issue with my nightscout build. I built it through Northflank/github. When I try to use remote commands from Nightscout or the Loop Caregiver app, I get a token error. After researching, I thought it might be how the APN key is input into Northflank - you can't put each line on a separate line in the variables. Putting a '\n' after each line break didn't work either. I have also checked the keys are all correct and also tried creating a new APN and revoking the old one. Does anyone have any other suggestions on what I can try or what could be the problem? The error message is below:

 
![IMG_E68A8FA82E55-1](https://github.com/nightscout/nightscout.github.io/assets/133823122/607dfaed-98ca-4692-8b4b-0ba2c83ee6ab)

Thanks,
Sarah

**Comment by psonnera** [comment]
Sorry I completely missed that one, did you follow these instructions? https://nightscout.github.io/vendors/northflank/new_user/#editing-variables-in-northflank (I guess yes). And did you eventually fix it?

**Comment by GraysonHunterNZ** [comment]
A northflank support guy let me know about the line break problem and to
put in the /n. Yes it’s all up and running now. Thanks for replying though
😊
