### ISSUE TITLE
Minor Azure Page: REMOVE the obsolete Video

### ISSUE THREAD

**Issue by FlyingToto** [nightscout/nightscout.github.io#195]
on the Azure doc section:
https://nightscout.github.io/vendors/azure/new_user/

remove the video completely 
or 
mention the warning about ignoring the Cosmo DB first and in red letters to avoid people getting more confused by starting the video and not realizing that Cosmo = Mongo etc... 
for instance rephrasing the paragraph :

from: 
This is a transcript of the original video you’ll find [here](https://www.youtube.com/watch?v=EDADrteGBnY), excluding the Cosmos database that isn’t fully compatible with Nightscout and can’t be deployed in some geographical areas.

to:
This is a transcript of the original video  which can not be used as-is anymore because the Cosmos(MongDB) database which was used at the time of the video isn't fully compatible with Nightscout and can't be deployed in some geographical areas.  For reference the obsolete video is [here](https://www.youtube.com/watch?v=EDADrteGBnY).

**Comment by psonnera** [comment]
Thank you very much. Merged.

**Comment by FlyingToto** [comment]
wow you guys are so fast!

**Comment by psonnera** [comment]
@FlyingToto that was easy: just had to copy/paste yours. Also removed the link from the migration page.
