### ISSUE TITLE
got billed 5.24 usd for Nightscout usage

### ISSUE THREAD

**Issue by gilimel** [nightscout/nightscout.github.io#198]
hi
i have 2 running apps (one for very long time that was migrated from Heroku) 
and suddenly i got billing
attached the usage - it seems my main app is running on 10 machines...

any help will be appreciated that i wont start getting billings in future.
thanks
Gili

![Screenshot 2023-09-01 205531](https://github.com/nightscout/nightscout.github.io/assets/49213396/db92a354-7892-4718-85c6-57e0c5f058d9)

**Comment by psonnera** [comment]
Where is that Nightscout hosted?

**Comment by gilimel** [comment]
fly io
it added many machines apparently.
i now removed them... i suggest to define explicitly number of machines to
scale to...

**Comment by psonnera** [comment]
Scaling to one is recommended now https://nightscout.github.io/vendors/fly.io/new_user/#step-6-deploy-nightscout but that wasn't specified at the time. Did you use the migration script when Heroku went billable?

**Comment by psonnera** [comment]
You're right it's missing here https://nightscout.github.io/vendors/fly.io/migrate/

**Comment by gilimel** [comment]
Yes…Sent from my iPhoneOn 1 Sep 2023, at 22:02, Patrick Sonnerat ***@***.***> wrote:﻿
You're right it's missing here https://nightscout.github.io/vendors/fly.io/migrate/

**Comment by psonnera** [comment]
https://github.com/nightscout/nightscout.github.io/commit/0505f5760142db7fdf3e96ce989ca8269fe95b33
