### ISSUE TITLE
device list(s)

### ISSUE THREAD

**Issue by ldesboro** [nightscout/nightscout.github.io#2]
Suggest merging:

http://nightscout.github.io/pdfs/CGM-Pebble-App-Install-Tutorial-FB.pdf

and

https://docs.google.com/spreadsheets/d/1q6-MszAhMI_6vNPKZSOAFyDAIRHMIgGbQQMwJHrZ1TI/edit#gid=0

(are there others too?)
##

**Comment by psonnera** [comment]
G4 being phased out, sending users to the Medtronic OTG phones list. https://docs.google.com/document/d/13OeqBaq01rpzcfsA1quDZgCJ3saJVgFob0IEqA4MCv8/edit
For Pebble please see https://nightscout.github.io/nightscout/wearable/#pebble-smartwatches
