### ISSUE TITLE
Fly.io will charge for dedicated IPv4 in January 1st

### ISSUE THREAD

**Issue by waltersf** [nightscout/nightscout.github.io#200]
According to https://community.fly.io/t/we-are-going-to-start-charging-for-dedicated-ipv4-in-january-1st/15970, Fly will charge for dedicated IPv4. 

Messages were sent in October, but I realize that many people (including me) were using a dedicated IPv4. They will charge $1.90 per month, but you can change to a shared IPv4. 

Could you please add a warning about this charging? Also, if people do not want to pay for it, they can use the `flyctl` command to release the dedicated address and ask for a shared one. I changed my app using the following commands:

```
$ flyctl auth login  # This will open a browser and ask me to authenticate 

$ flyctl app list
NAME    OWNER           STATUS          PLATFORM        LATEST DEPLOY
example-ns   personal        deployed        machines        2023-05-26T07:24:51Z


$ flyctl ips list -a example-ns
VERSION IP                      TYPE    REGION  CREATED AT
v4      137.66.11.78            public  global  2022-09-13T14:17:58Z
v6      3b09:8280:1::3:723c     public  global  2022-09-13T14:18:00Z

$ flyctl ips release 137.66.11.78 -a example-ns
Released 137.66.11.78 from example-ns

flyctl ips allocate-v4 --shared -a example-ns
v4      <new-ip-assigned> shared  global
```

Notice that you must change the ip `137.66.11.78` and the name example-ns accordingly. 

Best

**Comment by psonnera** [comment]
I will add that to the documentation but AFAIK the install guide doesn't make you use a dedicated IP by default. How did you deploy?

**Comment by waltersf** [comment]
> I will add that to the documentation but AFAIK the install guide doesn't make you use a dedicated IP by default. How did you deploy?

You are correct. New deployments are using shared IPv4. But old ones, migrated from Heroku, are using dedicated ones. Both cases I checked were migrated from Heroku.

Thanks!

**Comment by psonnera** [comment]
Great. Now the issue is they removed the web terminal so the documentation is broken.

**Comment by psonnera** [comment]
Adding draft for reference https://github.com/nightscout/nightscout.github.io/commit/1cc8ee56f145d86ea2fb5dd7ffe0d865064f6a03. Fly.io needs rework for the missing web terminal though. That's to be done with https://github.com/nightscout/nightscout.github.io/issues/201

**Comment by psonnera** [comment]
@waltersf the "good" news is they removed the migration wizard, so this should only be for currently migrated users. https://fly.io/docs/rails/getting-started/migrate-from-heroku/

**Comment by psonnera** [comment]
https://github.com/nightscout/nightscout.github.io/commit/1cc8ee56f145d86ea2fb5dd7ffe0d865064f6a03
