### ISSUE TITLE
Blue background on web

### ISSUE THREAD

**Issue by FalconEagleTest** [nightscout/nightscout.github.io#202]
hi,
I need your help,
for some reason, the view on the web became all blue, don't know why or how, I didn't change anything, it's on all my devices,
please help
thanks.
![image](https://github.com/nightscout/nightscout.github.io/assets/34710362/e1ce8354-7c71-4258-9898-70a7cbfb859b)

**Comment by psonnera** [comment]
Zoom out to see the treatment. You'll find it here too https://nightscout.github.io/nightscout/reports/#treatments and you should delete it

**Comment by FalconEagleTest** [comment]
> Zoom out to see the treatment. You'll find it here too https://nightscout.github.io/nightscout/reports/#treatments and you should delete it

zoom out didnt changed it.
i deleted every treatment and its gone, but why does every treatment turns everything to blue? any way to change that?

thanks
![image](https://github.com/nightscout/nightscout.github.io/assets/34710362/9bf60dbf-c150-4dbc-9b57-65150bd04ab4)

**Comment by psonnera** [comment]
@FalconEagleTest what did the treatments look like? Scroll down to see a particularly large one (either carbs or insulin units). Red cross is for deletion.

**Comment by FalconEagleTest** [comment]
don't see something special, just now i gave bolus of 0.3 and all blue again.
this blue thing started today, never had that before.
![image](https://github.com/nightscout/nightscout.github.io/assets/34710362/c5276628-3dde-4586-b0ec-d27c264dcb29)

**Comment by FalconEagleTest** [comment]
one more thing as I continue to check all those numbers got weird and nothing like what I have in the app
any way to resync nightcloud and fix all that?
thanks.
@psonnera 
![image](https://github.com/nightscout/nightscout.github.io/assets/34710362/ee5b90c7-93b4-405c-bb03-f13eee382558)

**Comment by FalconEagleTest** [comment]
found the problem :-)
the profile was wrong, for some reason nightscout thought I was on a different profile.
thanks anyway.

**Comment by psonnera** [comment]
Wow that is so strange.
