### ISSUE TITLE
Error in documentation uploader/setup.md: change `CONNECT_SHARE_SERVER` to `CONNECT_SHARE_REGION`

### ISSUE THREAD

**Issue by oliver-0815** [nightscout/nightscout.github.io#204]
There is an error in the documentation for for the Dexcom upload section. `CONNECT_SHARE_SERVER` should be replaced by `CONNECT_SHARE_REGION`.

https://github.com/nightscout/nightscout.github.io/blob/d574e9cafd108ec15aa9fa80050303c7c9470896/docs/uploader/setup.md?plain=1#L101

should be changed to

```
`CONNECT_SHARE_REGION` (must be set to `ous` if outside of the US, else don't add this variable)</br>
```

**Comment by psonnera** [comment]
Thank you https://github.com/nightscout/nightscout.github.io/commit/8a1165a9e76c4f0581a3899a8d658d2514e95f9f
