### ISSUE TITLE
Dexcom utility for switching between mg/dl and mmol/l

### ISSUE THREAD

**Issue by SugarBots** [nightscout/nightscout.github.io#21]
I'd love to see a preference setting on the uploader to switch between mg/dl and mmol/l  - is anyone able to point me in the right direction to add the conversion rate? (x/18.1)

Thanks in advance!
##

**Comment by psonnera** [comment]
Addressed in documentation.
https://nightscout.github.io/nightscout/new_user/#step-4-fork-and-deploy-cgm-remote-monitor
