### ISSUE TITLE
no data from dexcom g7 to nightscout hosted on nightflank

### ISSUE THREAD

**Issue by jasmines** [nightscout/nightscout.github.io#213]
Find attached log.
It seems I have an authentication error, but I double checked all my env vars and they're correct.
Please help!
[all_20240630T090255.042-20240630T090422.385.log](https://github.com/user-attachments/files/16043509/all_20240630T090255.042-20240630T090422.385.log)

**Comment by psonnera** [comment]
@jasmines I'm really sorry I completely lost this one... hopefully you've managed to fix it since then?
This GitHub repo is regarding documentation, not support.
For better help, join us on Facebook https://www.facebook.com/groups/cgminthecloud or in Discord https://discord.gg/zg7CvCQ
