### ISSUE TITLE
Suggestions for cleaning up all the online documentation

### ISSUE THREAD

**Issue by jenm999** [nightscout/nightscout.github.io#22]
The “front page” of this project, and where all inquiring minds should be directed: http://nightscout.github.io/ .  Once these changes are made, I suggest putting this at the very top of the Facebook group because the veterans are having to direct newbies all the time.

The above “front page” has too many links on it and they are not organized.  From what I can discern there should be 3 major sections:
1.  Quickstart Guide (rename Quickstart, keep subsections)
2.  Wiki (make this a section)
3.  Github (the code) 

Suggested specific edits:
1.  Delete Guides header, Quickstart button and Wiki button
2.  Rename Groups to Links 
3.  Move hackingtype1.com link from the Github menu to Links
4.  Move trello link from Github menu to Links and label it like you did the Facebook link with what the heck trello is (seems to be some kind of development hangout?)
5.  Why is there a link to “this website” under Github 
6.  Delete docs – these are all pages on the wiki; it’s just confusing
7.  Create page on the wiki for Azure free account management and copy over the info from the posts section
8.  Create page on the wiki for Subdued color scheme and copy over the info from the posts section
9.  Delete posts section
10. Delete Azure and Subdued posts from the quickstart guide

Copy this document after the three major sections identified above https://attachment.fbsbx.com/file_download.php?id=300539976776929&eid=ASvW380xAmqDoxvM64ityWfa-R8zYLe42AHM5Og7Gj2NKlPUM6JweOx2qA7l7btATAY&inline=1&ext=1403142771&hash=ASu5AewhgLakw7ZN 
Then delete it from Facebook

Delete this as it’s now been integrated into the Quickstart Guide
https://www.facebook.com/groups/cgminthecloud/566399763481284/

Create a page in the wiki called Dexcom Error Codes and then copy this post to that page:
https://www.facebook.com/notes/cgm-in-the-cloud/dexcom-error-codes/561005774020683
Then delete it from Facebook

Reconcile this document: https://attachment.fbsbx.com/file_download.php?id=308379319313798&eid=AStWpp_ptNyRFj_KrOuo0sYSVSeFDIPrsQIfjJpV2brwAsNrQDVQKgod73zm3u-ULZI&inline=1&ext=1403142981&hash=ASupexQRvVU9ZMby
With the What Uploaders work best? Link on the wiki.
Then delete it from Facebook

That’s all for now, but I’ll have more suggestions on cleaning up the wiki another day.

Oh, and let’s add a snazzy image to the front page.  Maybe this one?  https://fbcdn-sphotos-d-a.akamaihd.net/hphotos-ak-xpf1/t1.0-9/10408646_786591064708847_4157694538599979556_n.jpg

THANKS!

Jen Montbach
##

**Comment by psonnera** [comment]
Obsolete.
