### ISSUE TITLE
Fly.io free allowances have been suset

### ISSUE THREAD

**Issue by ninelore** [nightscout/nightscout.github.io#226]
Fly.io has sunset all plans as well as free allowances on 2024-10-07 and is only offering a pay-as-you-go model going forward. Plans and allowances on existing Users will be honored.

New pricing can be found [here](https://fly.io/docs/about/pricing/#started-fly-machines), however tldr the lowest end machine, which is enough for Nightscout, costs between $1.94 and $3.61 depending on the datacenter.

https://fly.io/docs/about/pricing/

**Comment by psonnera** [comment]
https://github.com/nightscout/nightscout.github.io/commit/06ba040effbd0034c94ff1c145d89473fbdacd15
