### ISSUE TITLE
How to contribute...

### ISSUE THREAD

**Issue by gregwaehner** [nightscout/nightscout.github.io#23]
Ben - Looking into how to add my "dexcom-uploader" instructions to the "guides/06-android-app.html.md". The prose.io site looks very helpful -- I've never used it before, but can see how it's tagging content and then using that for rendering. 

Questions (so I don't create chaos in trying to contribute)
1.  All the images are in "i.imgur.com." Is there a reason for this, or should the images as part of the guides be in the nightscout.github.io src, for example, "src/img/" in order to have a complete website package version controlled?
1. My question #1 may be related to this... but I'm not seeing how the default branch (source) becomes the "master" branch. I'm assuming the "master branch" is what is actually deployed as the website. If it's irrelevant, then cool -- I'm just trying to understand the end-to-end layout. Where this fits into reality is that I can edit the /guides/06-android-app.html.md file, but I can't figure out how the "nightscout.github.io/posts/01-quickstart/" content is rendered -- it looks like it's a union of the individual guides, but I can't confirm that, so I don't know if I need to make the edits twice.
2. Procedurally, I have forked the nightscout.github.io. Do I create my own branch just to edit the doc, or do I edit my forked-version of the doc?

Thanks.
- Greg
##

**Comment by psonnera** [comment]
Obsolete.
