### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by ebarendt** [nightscout/nightscout.github.io#25]
You say on the [wiki](https://github.com/nightscout/nightscout.github.io/wiki/Can-I-sell-Nightscout%3F) that the software is MIT licensed, but "If you sell this software we would consider it stealing." The [MIT license](http://opensource.org/licenses/MIT) specifically allows selling the software.

I have no intention of selling it, but you should definitely clarify.
##

**Comment by psonnera** [comment]
https://github.com/nightscout/cgm-remote-monitor#license
