### ISSUE TITLE
suggest breaking up quickstart

### ISSUE THREAD

**Issue by bewest** [nightscout/nightscout.github.io#4]
Quickstart guide, especially with my addition of pebble and pictures, has grown a bit.

People on facebook are requesting a simple "step by step" guide.  Perhaps it makes sense to break up the quickstart into sections, which each section on it's own page.  Reviewing `jade` and `docpad` stuff.
##

**Comment by psonnera** [comment]
I'm not sure that many people still use it... https://nightscout.github.io/nightscout/wearable/#pebble
