### ISSUE TITLE
Docpad project missing from current directory

### ISSUE THREAD

**Issue by Antonia-place** [nightscout/nightscout.github.io#44]
Hello all,
I follow the tutorial from "https://github.com/nightscout/nightscout.github.io" but I have some problema. I receive this message: "Warning: We couldn't find an existing DocPad project inside your current directory". A attach one print screen with this error.
Please advise me in order to succeed to install this application.

Thank you,
Mihai 
![capture](https://cloud.githubusercontent.com/assets/10450789/5909183/c899687a-a5b6-11e4-89b8-afe5c5266fa9.PNG)
Popa

**Comment by bewest** [comment]
Ah, try `cd ..; ./node_modules/.bin/docpad run`  the tool expects to run from the root of the project, and you can give the full path like: `./node_modules/.bin/docpad`.

Sorry about the confusion.
If you don't like that you can try: `npm install -g docpad` and then simply run `docpad`, assuming your system is set up such that globally installed modules show up in your `PATH` automatically.
If none of that makes sense, try just running it from the root of the project as mentioned above and visit `http://localhost:9778/` or similar to preview the site.  The pages visible on the front end mostly map to the `src/documents/` directory.  There's more info here: https://docpad.org/

**Comment by jasoncalabrese** [comment]
Are you really looking to edit the doc or do you just want to setup Nightscout?  You may want to start with http://www.nightscout.info/

**Comment by Antonia-place** [comment]
Hello all,
Thank you for support.
I setup Nightscout from this address: http://www.nightscout.info/ and it is work fine for the first time.
I succeeded to install this application and run docpad.
Thank again,
Mihai
