### ISSUE TITLE
Suggestions for Configure page

### ISSUE THREAD

**Issue by jimsiff** [nightscout/nightscout.github.io#45]
Here are a few suggestions for the Configure page used to generate QR codes:

REST Tab

1) Change "Azure site" text to "Nightscout site" to be more generic, supporting Heroku and other hosting providers.  Also, consider enlarging the text box so the user can see the entire URL they enter.

2) Automatically add /api/v1 to the Nightscout site entered by the user.  Currently, if a user enters what is asked for (Azure site) they will get a malformed REST API URL.  See below for a malformed URL example.

![screen shot 2015-01-29 at 10 34 48 am](https://cloud.githubusercontent.com/assets/6069420/5963650/f4893d32-a7a2-11e4-94ee-4f8d5083cbe6.png)

Mongo Tab

The Mongo tab seems confusing in general.  It doesn't follow the documentation on .info and some of the text is unclear.  

1) Can we leverage existing documentation on .info for Step 1; i.e. "Refer to the Nightscout documentation at http://www.nightscout.info/wiki/welcome/configuring-the-data-backend to configure your Mongo database.  We can modify the existing documentation / cheat sheet as required to accommodate using this auto-configure tool.

2) For Step 2, you're really asking for the Mongolab server hostname, port, and db name.  Can we change it to say something like "Enter your Mongo server, port, and database name here:" and increase the size of the text box so you can see all data entered.  Also, users can copy/paste this text directly from Mongolab.com.  Here's an example from one of my databases:

![screen shot 2015-01-29 at 11 29 00 am](https://cloud.githubusercontent.com/assets/6069420/5964663/bde6aeec-a7aa-11e4-9baa-54f3a4c8feae.png)

3) For step 3, if we leverage existing Nightscout documentation for this process, users will already have a db username and password.  You could change the text to read "Enter your database username and password"

4) There are many users with non-standard collection names.  I think we should accommodate this by adding a collection box, just as there is in the android-uploader preferences screen.  Set the default to entries and allow users to change as required.

5) Is the Format button required?  It seems to auto-format as I enter text.  

WebApp tab

1) The required section should include MONGO_CONNECTION as well as MONGO_COLLECTION.  This will accommodate users with existing databases that use non-standard collection names.  

2) Does it make sense to add a label of "Connection Strings" above the variables, values, and the custom label so users know where to enter them?

3) It would be a little easier to read if the variable name, value, and custom had a little more space in between them.

4) API_SECRET should be required, at least for anyone who has a REST URL configured.
##

**Comment by bewest** [comment]
Thanks for excellent feedback, Jim!  I'm hoping to break this up into smaller, bite-sized issues/checklist type of deal, and already started breaking things up by topic in #46.  Perhaps we can recruit some help to get this feedback processed and update the designs.
