### ISSUE TITLE
designing mongo config experience

### ISSUE THREAD

**Issue by bewest** [nightscout/nightscout.github.io#46]
From https://github.com/nightscout/nightscout.github.io/issues/45
### Mongo Tab

The Mongo tab seems confusing in general.  It doesn't follow the documentation on .info and some of the text is unclear.  

1) Can we leverage existing documentation on .info for Step 1; i.e. "Refer to the Nightscout documentation at http://www.nightscout.info/wiki/welcome/configuring-the-data-backend to configure your Mongo database.  We can modify the existing documentation / cheat sheet as required to accommodate using this auto-configure tool.

2) For Step 2, you're really asking for the Mongolab server hostname, port, and db name.  Can we change it to say something like "Enter your Mongo server, port, and database name here:" and increase the size of the text box so you can see all data entered.  Also, users can copy/paste this text directly from Mongolab.com.  Here's an example from one of my databases:

![screen shot 2015-01-29 at 11 29 00 am](https://cloud.githubusercontent.com/assets/6069420/5964663/bde6aeec-a7aa-11e4-9baa-54f3a4c8feae.png)

3) For step 3, if we leverage existing Nightscout documentation for this process, users will already have a db username and password.  You could change the text to read "Enter your database username and password"

4) There are many users with non-standard collection names.  I think we should accommodate this by adding a collection box, just as there is in the android-uploader preferences screen.  Set the default to entries and allow users to change as required.

5) Is the Format button required?  It seems to auto-format as I enter text.  

@jimsiff
##

**Comment by psonnera** [comment]
Obsolete.
