### ISSUE TITLE
Improper encoding of special characters when using API auto configure tool

### ISSUE THREAD

**Issue by HandwovenBox** [nightscout/nightscout.github.io#59]
During configuration of the uploader app on my Samsung Galaxy S5, I used the API auto configure tool (http://nightscout.github.io/pages/configure/) to enter the URL and API secret into the uploader app.

My API secret includes special characters (for example, a "#", "%", or "$"). After completing setup, the app wasn't uploading data--it returned an error that indicated an authorization issue. When I reviewed the app settings, I realized that each special character had been converted to its encoded "%23", "%24", or "%25" which caused the error.

For example:
![auto_configure_nightscout_-_2018-07-08_01 34 41](https://user-images.githubusercontent.com/8444733/42417778-a45a6f94-824f-11e8-87d5-91fddc7b5ebe.png)

This occurred while I was using the 600SeriesAndroidUploader app but I imagine that it would be a problem regardless of the uploader app.

**Comment by psonnera** [comment]
Documentation updated to recommend not using special characters (difficult to handle with REST API).  https://nightscout.github.io/nightscout/new_user/#step-4-fork-and-deploy-cgm-remote-monitor
