### ISSUE TITLE
speech in Spanish not working

### ISSUE THREAD

**Issue by yosepito** [nightscout/nightscout.github.io#61]
Hi everyone: I have set up Spanish in the website showing BG values. I included LANGUAGE ES in Heroku (with language as variable on the left box and ES on the right one). While the site is now translated into Spanish (the text of IOB, COB...) the text spoken continues to be in English. What have I done wrong? 
The help says I should set the language IN THE SERVER. What does it mean?
Thanks in advance

**Comment by psonnera** [comment]
This should be filed in https://github.com/nightscout/cgm-remote-monitor like https://github.com/nightscout/cgm-remote-monitor/issues/6796
