### ISSUE TITLE
Dead link for Uploader setup

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#76]
Dead link:
http://nightscout.github.io/nightscout/uploader/setup.md

( found here: http://nightscout.github.io/nightscout/new_user/#step-5-uploader-setup
![image](https://user-images.githubusercontent.com/63544115/95573782-4527b100-0a2c-11eb-8365-37380400be9c.png)

Correct link:
http://nightscout.github.io/uploader/setup/

Ping @psonnera   :-)

**Comment by psonnera** [comment]
Good catch thanks. Fixed in next PR.

**Comment by bjornoleh** [comment]
@psonnera  I'll just add another little thing here:  :)

A textbox is duplicated here:
http://nightscout.github.io/nightscout/new_user/#step-4-fork-and-deploy-cgm-remote-monitor

![Screenshot_20201009-180913_Chrome](https://user-images.githubusercontent.com/63544115/95606584-d01fa000-0a5a-11eb-9d42-8d7d77b34ac2.jpg)

**Comment by psonnera** [comment]
Thanks. I will try to review better before doing PRs.

**Comment by psonnera** [comment]
Should be fixed with https://github.com/nightscout/nightscout.github.io/pull/90

**Comment by bjornoleh** [comment]
I'm sorry, but the link is still pointing to http://nightscout.github.io/nightscout/uploader/setup.md

Tested on Android Chrome, if that matters.

**Comment by logangreenwood** [comment]
not sure why im getting these messages. 
    On Monday, November 23, 2020, 11:27:15 AM CST, bjornoleh <notifications@github.com> wrote:  
 
 


I'm sorry, but the link is still pointing to http://nightscout.github.io/nightscout/uploader/setup.md

Tested on Android Chrome, if that matters.

**Comment by bjornoleh** [comment]
> not sure why im getting these messages.  On Monday, November 23, 2020, 11:27:15 AM CST, bjornoleh <notifications@github.com> wrote: I'm sorry, but the link is still pointing to http://nightscout.github.io/nightscout/uploader/setup.md Tested on Android Chrome, if that matters. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I can't see that you have been mentioned, so I guess you have subscribed to NS updates in Github? There should be a way to unsubscribe.

**Comment by bjornoleh** [comment]
https://github.com/nightscout/nightscout.github.io/blob/source/docs/nightscout/new_user.md

```
## Step 5: Uploader setup

</br>

[Configure your uploader](..\uploader\setup.md).


```

**Comment by psonnera** [comment]
Yes, this is killing me. That's a real pain that local server links correctly, gh-deploy also does but when it lands in the final page it's 404. https://github.com/nightscout/nightscout.github.io/pull/91

**Comment by bjornoleh** [comment]
Three is a charm :-)

**Comment by bjornoleh** [comment]
n-th time's a charm :)
