### ISSUE TITLE
New Nightscout Users/Troubleshooting: Include info about known issue with Dexcom username containing special characters

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#79]
New Nightscout Users/Troubleshooting should also include info about possible issues with Dexcom usernames containing special characters, please see below. I had this issue myself with an "@" after trying to use an email address as the username, and have helped a few others with this issue since that.

**New Nightscout Users**
![image](https://user-images.githubusercontent.com/63544115/95850293-e5454900-0d50-11eb-9e83-3fcee26a2fc5.png)
http://nightscout.github.io/nightscout/new_user/#step-4-fork-and-deploy-cgm-remote-monitor

**Troubleshooting section:**
![image](https://user-images.githubusercontent.com/63544115/95850919-d27f4400-0d51-11eb-8272-a421bfb77226.png)
http://nightscout.github.io/troubleshoot/troublehoot/#heroku-settings

---
**Documentation of the username issue here:** **https://github.com/Josef-A/sugarmate2nightscout/blob/master/how_to_fix_en.md**
![image](https://user-images.githubusercontent.com/63544115/95850237-cf378880-0d50-11eb-9f68-29b512c58ff3.png)

**Comment by psonnera** [comment]
In next PR, preview here https://psonnera.github.io/nightscout.github.io/troubleshoot/troublehoot/#heroku-settings

**Comment by bjornoleh** [comment]
Great! (Perhaps you could include a hint that it is possible to change the
email of the first Dexcom account to some other email address, before
creating a new Dex account with the preferred email. But this isn't
important)

fre. 16. okt. 2020, 23:02 skrev Patrick Sonnerat <notifications@github.com>:

**Comment by psonnera** [comment]
Very good idea. Doing it now.
