### ISSUE TITLE
who maintains http://www.nightscout.info/ landing page? I am not seeing this page in github. Link broken...

### ISSUE THREAD

**Issue by thomcost** [nightscout/nightscout.github.io#82]
The first link on the first page of http://www.nightscout.info/ is broken.

Get Started with Nightscout
Updated! General-purpose Nightscout setup, for Dexcom Share, xDrip+, or Spike
 Links to: http://www.nightscout.info/wiki/welcome/set-up-nightscout-using-heroku

Get an OOPs error.

I think it should goto here: https://nightscout.github.io/nightscout/new_user/

I would do a pull request...but i cannot find the page. Sorry.

I will keep looking.

**Comment by psonnera** [comment]
http://www.nightscout.info/ is being deprecated, use https://nightscout.github.io/ and here is the right place to PR
