### ISSUE TITLE
API_SECRET does not work?

### ISSUE THREAD

**Issue by Carmenberg** [nightscout/nightscout.github.io#85]
Hi 
In Heroku Config Vars the API_SECRET is set to a certain PW (12 characters) but when trying to launch Nightscout App the PW is not accepted?

Pls help

BR Mikkel

**Comment by old-square-eyes** [comment]
Try a new one without special characters. Just a guess. I've seen a few issues lately with Nightscout talking to Atlas. This might be the same (understand API_SECRET is for clients to talk to Nighscout). Worth a shot though.

**Comment by psonnera** [comment]
@Carmenberg please let me know if the solution is present in https://nightscout.github.io/troubleshoot/troublehoot/ or if some more troubleshooting regarding the API secret is necessary

**Comment by psonnera** [comment]
Closing inactive problem.
