### ISSUE TITLE
New NS site: "View" button after deployment in Heroku not working

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#88]
Hi @psonnera 

I have seen a few people reporting issues with getting their NS site to open when clicking the "View" button after deployment in Heroku. It seems that opening their url manually is working fine, so the deployment must have been successful after all. 

![image](https://user-images.githubusercontent.com/63544115/99875786-877b0b00-2bf2-11eb-94ab-937fd5b39320.png)

Perhaps add a hint to the guide about this, and possibly also in the troubleshooting?
http://nightscout.github.io/nightscout/new_user/#step-4-fork-and-deploy-cgm-remote-monitor

**Comment by bjornoleh** [comment]
One of the reports in CGMITC:
https://www.facebook.com/groups/cgminthecloud/permalink/3563458747108689/

**Comment by psonnera** [comment]
Yes, included in next PR. With clarifications for ndw users and connection string troubleshooting.

**Comment by bjornoleh** [comment]
Thanks!
