### ISSUE TITLE
simple set of graphics/pictures showing OTG cable how/why

### ISSUE THREAD

**Issue by bewest** [nightscout/nightscout.github.io#9]
A simple small suite of graphics that can be used on a web page to show what the OTG usb cable, why it's important (it's function in controlling master/slave relationship) and how to use it.

Maybe a cartoon/graphic and a picture showing?
Or a picture overlaid with text showing what's happening?

If someone can link the appropriate photos to use in a doc/comment somewhere I'll create page for it.
##

**Comment by psonnera** [comment]
Will G4 obsolescence, will soon not be an issue anymore.
https://www.dexcom.com/obsolescence#:~:text=Upcoming%20Obsolescence%20for%20the%20United,Platinum%2FG5%20Mobile%20CGM%20Systems*&text=Further%2C%20Dexcom%20Studio%20will%20no,software%20on%20December%2031st%2C%202020.
