### ISSUE TITLE
Basal-bolus insulin not showing on nightscout

### ISSUE THREAD

**Issue by neonser** [nightscout/nightscout.github.io#92]
Hi everyone

I have migrated to Atlas following this guide https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/ 
to continue using nightscout, and now i see glucose levels and calibrations but i don't see insulin boluses.

I have the last xdrip version (xDrip-plus-20200713-e14bae1.apk) and i think i have the necessary variables in heroku settings.

Now I can't use Nightscout reporting to correctly see the results obtained.

I have tried to find a solution on the internet but I have not seen anything. If you need more information, please ask me.

Thanks in advance.

(Forgive my bad English but I am Spanish and I am using a translator)

**Comment by StephenBrown2** [comment]
I think there may be more information necessary, but first this issue should probably be on the [cgm-remote-monitor](https://github.com/nightscout/cgm-remote-monitor/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) repository rather than this one.

Sorry I don't have more help at this time.

**Comment by neonser** [comment]
Thank you very much for answering.

I will put the issue in cgm-remote-monitor repository, to see if there are any answers.

**Comment by neonser** [comment]
The insulin is already shown in Nightscout since yesterday, curiously, without changing anything.

I have been surprised because I don´t know how it has been solved.

Thank you for your attention

**Comment by psonnera** [comment]
Does not apply to documentation. Closing.
