### ISSUE TITLE
Minor correction in wording needed.

### ISSUE THREAD

**Issue by TerrysNightscout** [nightscout/nightscout.github.io#94]
Please change the wording to read **may** instead of **will** in this statement. In over 3 years of use as a single user, I have never had to clean or delete the data.                                                                      
     Free databases like M0 Sandbox provided by Atlas will only hold a limited amount of data (512MB) and you will eventually need to manually cleanup. You can extend the capacity to 2 and 5GB paying an M2 or M5 Shared cluster.

**Comment by psonnera** [comment]
@TerrysNightscout please check current release matches your request.
