### ISSUE TITLE
Change in BG_TARGET_BOTTOM

### ISSUE THREAD

**Issue by TerrysNightscout** [nightscout/nightscout.github.io#96]
In 2019 the ADA and other medical groups announced and published new guidelines for T1Ds and set the NEW ranges as 70-180 SG/BG with >70% TIR. We should show this on our Heroku graphs and alarms/alerts as well. BG_TARGET_BOTTOM (80) should be (70)!

**Comment by psonnera** [comment]
Maybe this one should find its place in https://github.com/nightscout/cgm-remote-monitor/issues/new/choose directly?
