### ISSUE TITLE
Document Heroku roll-back 

### ISSUE THREAD

**Issue by psonnera** [nightscout/nightscout.github.io#98]
Might be useful after mistakes, to return to a known good point. In the troubleshooting page.

**Comment by bjornoleh** [comment]
Hi, I just had some use of this "Roll back to here" feature (which I know where to find in Heroku) and was thinking about giving the link to someone else. But it seems it hasn't made it into the docs yet.

Just a friendly reminder :-)

ps: The NS release of yesterday killed remote overrides for iOS Loop, hence the need to roll back. It seems the release has not been announced yet, so hopefully not too many will be affected. 
https://github.com/nightscout/cgm-remote-monitor/issues/7141

**Comment by bjornoleh** [comment]
A potential screenshot for this, since I had it handy just now:

<img width="599" alt="Skjermbilde 2021-10-25 kl  21 15 08" src="https://user-images.githubusercontent.com/63544115/138757412-53aa562d-b817-497a-b215-fb5fbe846a76.png">

**Comment by psonnera** [comment]
Implemented in https://github.com/nightscout/nightscout.github.io/commit/8b03ba67edce9315a947e43a64adcdbe4da26253
