### ISSUE TITLE
Input data from Apple Health?

### ISSUE THREAD

**Issue by hamzaranjha** [nightscout/nightscout.github.io#99]
Hi,

I'm currently using the nightscout service to retrieve data from my miamiao device via spike+. This is then sent to my Sugarmate app from where I log my carbs and bolus. As Sugarmate provides a food database to easily find the carbs iv eaten i'd prefer to use this however if there is a way for me to have a searchable food directory in nightscout, please let me know.

Unfortunately Sugarmate doesn't show me my Insulin On Board which is very useful info in predicting hypos. I see that Nightscout does in fact have an insulin on board calculator and so I'd like to use that however I have an issue where my nightscout site only contains bg readings and not my carb and bolus inputs.

Is there a way for me to sync this data which I am inputting from my sugarmate app (this data also syncs with apple health) to my nightscout app allowing me to input insulin/carb data via sugarmate but open nightscout to check my insulin on board?

Any help will be greatly appreciated! 

And also thank you for creating this service, it has been the sole reason I have managed to reduce my hba1c down so drastically!

Best Wishes,
Hamza

**Comment by psonnera** [comment]
You can use Nightscout food database https://nightscout.github.io/nightscout/setup_variables/#food-custom-foods to create customized foods.
When entering treatments in Nightscout you can specify food characteristics https://nightscout.github.io/nightscout/discover/#add-a-treatment-careportal .
Nightscout will only display the information it receives from Sugarmate, you might want to request this feature by contacting josh@sugarmate.io
